### ISSUE TITLE
Support ES6

### ISSUE THREAD

**Issue by tadatuta** [borschik/borschik#120]
Now build fails in production mode with`Error: Unexpected token: operator (>) (line: 5751, col: 48, pos: 258196)` on fat arrow functions.

**Comment by doochik** [comment]
ES6 support is in progress in UglifyJS. I'll update deps as far as they release new version

**Comment by sbmaxx** [comment]
Any updates here?

**Comment by tadatuta** [comment]
@sbmaxx 
There's `harmony` branch in UglifyJs, which is quite fine for far. We use it in a fork: https://github.com/birhoff/borschik/tree/harmony

**Comment by sbmaxx** [comment]
Альтернатив нет? Нужен борщик, енб-борщик с ES6 :/

**Comment by tadatuta** [comment]
can we optionally replace `UglifyJs` with https://github.com/babel/babili for ES6 cases?

**Comment by tadatuta** [comment]
@sbmaxx 

I released https://www.npmjs.com/package/borschik-tech-babili

here's how it should be used with `ENB`:
```js
[techs.borschik, {
    source: '?.js',
    target: '?.min.js',
    tech: 'babili'
}]
```

Tests passed on my project.
