### ISSUE TITLE
Freeze + Windows 7 + Node 6.8.0+ = bug

### ISSUE THREAD

**Issue by xdghcnt** [borschik/borschik#129]
New behaviour of Node Path https://github.com/nodejs/node/pull/8541#issuecomment-248388483 сauses ENOENT error.
"C:Dir1/Dir2" passed to mkdirSync here:
https://github.com/borschik/borschik/blob/master/lib/freeze.js#L437

**Comment by blond** [comment]
It is reproduced on all `Node.js` versions or only `6.x`?

I tried the following code (launched not in Windows):

```js
"C://Dir1/Dir2".split(path.sep); // [ 'C:', '', 'Dir1', 'Dir2' ]

path.join('C:', '', 'Dir1', 'Dir2'); // 'C:/Dir1/Dir2'
```

It works the same with `Node.js 4` and `Node.js 6`. 

In nodejs/node#8541 I see that they are talking about the `path.resolve` but not about the `path.join`.

Could you tell me which `path` value in [this string](https://github.com/borschik/borschik/blob/master/lib/freeze.js#L420).

**Comment by xdghcnt** [comment]
On versions since 6.8.
My path is ok.
Actually this is what happens:
```javascript
path.join('', 'C:'); // C:.
path.join('C:.', 'Dir1'); // C:Dir1
path.join('C:Dir1', 'Dir2'); // C:Dir1/Dir2
```

**Comment by tsofist** [comment]
any updates?

**Comment by phonegapalex** [comment]
Any news? Will it be fixed?

**Comment by tsofist** [comment]
Anybody home? :)
